"""empty message

Revision ID: bbe6763dc12d
Revises: ccdb12289e01
Create Date: 2025-01-20 05:42:20.346956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe6763dc12d'
down_revision = 'ccdb12289e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LGS.Part',
    sa.Column('PartID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=64), nullable=False),
    sa.Column('Name', sa.String(length=256), nullable=False),
    sa.Column('UnitRef', sa.Integer(), nullable=True),
    sa.Column('CategoryRef', sa.Integer(), nullable=False),
    sa.Column('StorePositionRef', sa.Integer(), nullable=False),
    sa.Column('QRCode', sa.Text(), nullable=True),
    sa.Column('QRCodeImage', sa.String(length=256), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['CategoryRef'], ['LGS.Category.CategoryID'], ),
    sa.ForeignKeyConstraint(['StorePositionRef'], ['LGS.StorePosition.StorePositionID'], ),
    sa.ForeignKeyConstraint(['UnitRef'], ['GNR.Unit.UnitID'], ),
    sa.PrimaryKeyConstraint('PartID'),
    sa.UniqueConstraint('Code'),
    sa.UniqueConstraint('Name')
    )
    with op.batch_alter_table('LGS.StorePosition', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'LGS.Store', ['StoreID'], ['StoreID'])

    with op.batch_alter_table('SYS1.User', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'GNR.Party', ['PartyRef'], ['PartyID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SYS1.User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('LGS.StorePosition', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('LGS.Part')
    # ### end Alembic commands ###
