"""empty message

Revision ID: cc9fdb9dd14f
Revises: 3dcdd31f932b
Create Date: 2025-01-20 00:52:25.705648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9fdb9dd14f'
down_revision = '3dcdd31f932b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LGS.Category',
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=64), nullable=False),
    sa.Column('Name', sa.String(length=256), nullable=False),
    sa.Column('PricingMethod', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('CategoryID'),
    sa.UniqueConstraint('Code'),
    sa.UniqueConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LGS.Category')
    # ### end Alembic commands ###
