"""empty message

Revision ID: ccdb12289e01
Revises: cc9fdb9dd14f
Create Date: 2025-01-20 03:56:13.844338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdb12289e01'
down_revision = 'cc9fdb9dd14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GNR.Party',
    sa.Column('PartyID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=50), nullable=True),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('Gender', sa.String(length=20), nullable=True),
    sa.Column('Mobile', sa.String(length=20), nullable=True),
    sa.Column('EducationDegree', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('PartyID')
    )
    op.create_table('GNR.Unit',
    sa.Column('UnitID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=256), nullable=False),
    sa.Column('AbbreviatedName', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('UnitID'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('LGS.Store',
    sa.Column('StoreID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=128), nullable=False),
    sa.Column('Code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('StoreID')
    )
    op.create_table('LGS.StorePosition',
    sa.Column('StorePositionID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=64), nullable=False),
    sa.Column('Name', sa.String(length=256), nullable=False),
    sa.Column('StoreID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['StoreID'], ['LGS.Store.StoreID'], ),
    sa.PrimaryKeyConstraint('StorePositionID'),
    sa.UniqueConstraint('Code'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('SYS1.User',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('PartyRef', sa.Integer(), nullable=False),
    sa.Column('IsAdministrator', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['PartyRef'], ['GNR.Party.PartyID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SYS1.User')
    op.drop_table('LGS.StorePosition')
    op.drop_table('LGS.Store')
    op.drop_table('GNR.Unit')
    op.drop_table('GNR.Party')
    # ### end Alembic commands ###
